events{}
http {
    upstream backend{
        server 34.229.84.**:80;
        server 44.222.212.1**:80;
        server 34.207.143.2**:80 backup;   # only used if the above are down
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend/;
        }
    }
}